### ISSUE TITLE
Script not working 

### ISSUE THREAD

**Issue by ghost** [koenrh/delete-tweets#105]
When I try it I get 

```
root@DietPi:~# delete-tweets --until 2021-01-01 tweet.js
Traceback (most recent call last):
  File "/usr/local/bin/delete-tweets", line 6, in <module>
    from deletetweets.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/deletetweets/__main__.py", line 7, in <module>
    from deletetweets import deletetweets
ImportError: cannot import name deletetweets
```

I am using a Pi with DietPi installed, followed the guide to the letter, not sure where I went wrong?

**Comment by ghost** [comment]
The suggestion of commenting out one line and adding another from here https://github.com/koenrh/delete-tweets/issues/71

worked....well I think it has, it says its deleting tweets....time will tell, its got a few to do
