### ISSUE TITLE
Some Errors

### ISSUE THREAD

**Issue by onursaner** [koenrh/delete-tweets#115]
How can I overcome the following problem? Can you help me?

Traceback (most recent call last):
  File "/Users/......./Library/Python/3.9/bin/./delete-tweets", line 8, in <module>
    sys.exit(main())
  File "/Users/......./Library/Python/3.9/lib/python/site-packages/deletetweets/__main__.py", line 54, in main
    deletetweets.delete(args.file, args.since_date, args.until_date, filters, args.spare_ids,
  File "/Users/......./Library/Python/3.9/lib/python/site-packages/deletetweets/deletetweets.py", line 59, in delete
    with io.open(tweetjs_path, mode="r", encoding="utf-8") as tweetjs_file:
FileNotFoundError: [Errno 2] No such file or directory: 'tweet.js'

**Comment by riggsiwoo** [comment]
same here
