### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by Lewiscowles1986** [koenrh/delete-tweets#6]
Fancy a patch for python3 and systems that python doesn't default to "utf8" encoding?

Otherwise the following errors are generated

### Python2/3 print

```
$ python deletetweets.py -d 2013-10-01
  File "deletetweets.py", line 30
    print "Deleting tweet #{0} ({1})".format(tweet_id, tweet_date)
                                    ^
SyntaxError: invalid syntax
```

### UTF-8 windows bug

```
$ python deletetweets.py -d 2015-12-31
Traceback (most recent call last):
  File "deletetweets.py", line 63, in <module>
    main()
  File "deletetweets.py", line 59, in main
    delete(api, args.date, args.restrict)
  File "deletetweets.py", line 18, in delete
    for row in csv.DictReader(file):
  File "C:\Program Files\Python36\lib\csv.py", line 111, in __next__
    self.fieldnames
  File "C:\Program Files\Python36\lib\csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
  File "C:\Program Files\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2268: character maps to <undefined>
```

**Comment by nazimjamil** [comment]
I've encountered the same issue r.e. python print on macOS and have resolved it by modifying the line to
```
new_string = "Deleting tweet #{0} ({1})"
                print (new_string.format(tweet_id, tweet_date))
```

Might help you in the short term.

**Comment by Lewiscowles1986** [comment]
There is a PR for python3 compatibility, there were a few issues with Python2
