### ISSUE TITLE
Problems with 'twitter.Api' and 'module' object not callable

### ISSUE THREAD

**Issue by zhushazang** [koenrh/delete-tweets#72]
Hello there.

First, using Linux and Python 3.7 here. Then, after install delete-tweets the first error was:

`delete-tweets tweet.js                                                                                                                     23:31
Traceback (most recent call last):
  File "/home/rodolfo/.local/bin/delete-tweets", line 8, in <module>
    sys.exit(main())
  File "/home/rodolfo/.local/lib/python3.7/site-packages/deletetweets/__main__.py", line 53, in main
    deletetweets.delete(args.file, args.until_date, filters, args.spare_ids, args.min_likes, args.min_retweets, args.dry_run)
  File "/home/rodolfo/.local/lib/python3.7/site-packages/deletetweets/deletetweets.py", line 64, in delete
    api = twitter.Api(consumer_key=os.environ["TWITTER_CONSUMER_KEY"],
`
Then, changing it manually to "twitter.api" i received the next error:

`delete-tweets tweet.js                                                                                                                     23:31
Traceback (most recent call last):
  File "/home/rodolfo/.local/bin/delete-tweets", line 8, in <module>
    sys.exit(main())
  File "/home/rodolfo/.local/lib/python3.7/site-packages/deletetweets/__main__.py", line 53, in main
    deletetweets.delete(args.file, args.until_date, filters, args.spare_ids, args.min_likes, args.min_retweets, args.dry_run)
  File "/home/rodolfo/.local/lib/python3.7/site-packages/deletetweets/deletetweets.py", line 64, in delete
    api = twitter.Api(consumer_key=os.environ["TWITTER_CONSUMER_KEY"],
`

Best regards.

**Comment by koenrh** [comment]
Thank you for reporting! I think I have fixed this bug in [v1.0.5](https://pypi.org/project/delete-tweets/). Could you try reinstalling the package and try again?

Please reopen this issue if the latest version did not fix it.
